// Generated by https://quicktype.io

export interface IClientsResponse {
    id:        string;
    name:      string;
    lastname:  string;
    email:     string;
    gender:    string;
    createdAt: string;
    updatedAt: string;
}
