// Generated by https://quicktype.io

export interface ICategory {
    id:          string;
    name:        string;
    slug:        string;
    description: string;
    image:       string;
    createdAt:   string;
    updatedAt:   string;
}
