// Generated by https://quicktype.io

export interface IUsersResponse {
    id:        string;
    name:      string;
    lastname:  string;
    email:     string;
    avatar:    string;
    createdAt: string;
    role:      Role;
}

interface Role {
    id:        string;
    name:      string;
    createdAt: string;
    updatedAt: string;
}
