// Generated by https://quicktype.io

export interface IProvider {
    id:        string;
    name:      string;
    direction: string;
    email:     string | null;
    phone:     string | null;
    status:    boolean;
    createdAt: string;
    updatedAt: string;
}
